### ISSUE TITLE
Not showing anything

### ISSUE THREAD

**Issue by ctbritt** [etriebe/combat-estimate#5]
Getting this when I try to use the module: 

<img width="799" alt="Screen Shot 2022-05-06 at 12 35 47 PM" src="https://user-images.githubusercontent.com/4516034/167174941-fcdf11b1-4521-4d03-970e-4b92561ff8ad.png">

ANd this is the error the console is throwing: 

```
Uncaught (in promise) ReferenceError: SFLOCALCONSTS is not defined
[Detected 1 package: combat-estimate]
    at Function.getSystemVariableForObject (FoundryUtils.js:40:7)
    at Function.getCreatureTypeForActor (ActorUtils.js:11:25)
    at new NPCActor5e (NPCActor5e.js:14:40)
    at Function.getActorObject (ActorUtils.js:44:14)
    at CombatEstimateDialog.populateCombatants (dialog.js:80:31)
    at CombatEstimateDialog.activateListeners (dialog.js:37:8)
    at CombatEstimateDialog._render (foundry.js:3090:10)
    at async CombatEstimateDialog._render (foundry.js:3764:5)
```

**Comment by ctbritt** [comment]
Also getting a lot of errors like this: 
```
Error parsing attack information for Miabella (Copy), FRBdmL3AvHILU7RD. Error: TypeError: Cannot read properties of null (reading 'abilityMod')
```

**Comment by etriebe** [comment]
Good find! Probably an old reference to the module I had worked on before. Do you mind attaching that actor object?

--Eric Triebe

________________________________

**Comment by etriebe** [comment]
Fixed first issue with commit. Release 1.0.7 has that fix. @ctbritt 

https://github.com/etriebe/combat-estimate/commit/fea83489fdfbf70e8129780a115a6488fd6992b9

**Comment by etriebe** [comment]
Closing until I can get the actor causing issues. Other issue is resolved.
